name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain: ["blocksworld", "ferry", "satellite", "transport"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # - name: Install test dependencies
      #   run: |
      #     python -m pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest -s tests/test_trained_policies.py --domain ${{ matrix.domain }}
